"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { Spinner, ToastProvider } from "@/components/ui";
import { LayoutDashboard, Search, Upload, Target, Users, Mic, ListChecks, FlaskConical, ShieldQuestion, Globe2, GitBranch, Moon, Sun, PanelLeftClose, PanelLeftOpen, Command, Sparkles, LogOut } from "@/components/icons";
import { fetchSession, signOut as signOutRequest, type SessionUser } from "@/lib/auth";
import type { Product } from "@/lib/types";

const NAV_ITEMS = [
  { href: "/dashboard", label: "Dashboard", icon: LayoutDashboard, shortcut: "1" }, { href: "/discover", label: "Discover", icon: Target, shortcut: "2" }, { href: "/import", label: "Import", icon: Upload, shortcut: "3" }, { href: "/opportunities", label: "Opportunities", icon: Target, shortcut: "4" }, { href: "/personas", label: "Personas", icon: Users, shortcut: "5" }, { href: "/interviews", label: "Interviews", icon: Mic, shortcut: "6" }, { href: "/features", label: "Features", icon: ListChecks, shortcut: "7" }, { href: "/experiments", label: "Experiments", icon: FlaskConical, shortcut: "8" }, { href: "/assumptions", label: "Assumptions", icon: ShieldQuestion, shortcut: "9" }, { href: "/research", label: "Research", icon: Globe2, shortcut: "0" }, { href: "/tree", label: "Solution Tree", icon: GitBranch, shortcut: "T" },
];

export default function AppLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const router = useRouter(); const [light, setLight] = useState(false); const [sidebarOpen, setSidebarOpen] = useState(true); const [product, setProduct] = useState(""); const [draftProduct, setDraftProduct] = useState(""); const [products, setProducts] = useState<Product[]>([]); const [chooseProduct, setChooseProduct] = useState(false); const [ready, setReady] = useState(false); const [onboarding, setOnboarding] = useState(false); const [mounted, setMounted] = useState(false); const [session, setSessionUser] = useState<SessionUser | null>(null);
  const productRef = useRef(product);
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setMounted(true); const isLight = localStorage.getItem("theme") === "light"; setLight(isLight); document.documentElement.classList.toggle("light", isLight); if (window.matchMedia("(max-width: 767px)").matches) setSidebarOpen(false);
    Promise.all([fetchSession(), fetch("/api/products", { cache: "no-store" }).then(response => response.ok ? response.json() as Promise<Product[]> : [])]).then(([user, ownedProducts]) => {
      if (user) setSessionUser(user);
      setProducts(ownedProducts);
      const savedProduct = localStorage.getItem("active-product") || "";
      const activeProduct = ownedProducts.find(item => item.id === savedProduct);
      if (activeProduct) { productRef.current = activeProduct.id; setProduct(activeProduct.id); }
      else setChooseProduct(true);
      setReady(true);
    }).catch(() => setReady(true));
  }, []);
  useEffect(() => { productRef.current = product; }, [product]);
  useEffect(() => { const originalFetch = window.fetch.bind(window); window.fetch = (input, init = {}) => { const request = input instanceof Request ? input : undefined; const url = typeof input === "string" ? input : input instanceof URL ? input.toString() : input.url; if (!url.startsWith("/api/") || url === "/api/products") return originalFetch(input, init); const headers = new Headers(request?.headers || init.headers); const context = productRef.current; if (context) headers.set("x-product-context", context); return originalFetch(input, { ...init, headers }); }; return () => { window.fetch = originalFetch; }; }, []);
  const selectProduct = (selected: Product) => { localStorage.setItem("active-product", selected.id); productRef.current = selected.id; setProduct(selected.id); window.dispatchEvent(new Event("active-product-changed")); setOnboarding(!selected.researchCount); if (selected.researchCount) setChooseProduct(false); };
  const saveProduct = async () => { const next = draftProduct.trim(); if (!next) return; const response = await fetch("/api/products", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: next }) }); if (!response.ok) return; const created = await response.json() as Product; setProducts(previous => previous.some(item => item.id === created.id) ? previous : [...previous, created]); selectProduct(created); setDraftProduct(""); };
  const handleSignOut = async () => { await signOutRequest(); router.replace("/"); };
  const initials = session ? session.name.trim().split(/\s+/).map(p => p[0]).join("").slice(0, 2).toUpperCase() : "";
  const toggleTheme = useCallback(() => setLight(prev => { const next = !prev; document.documentElement.classList.toggle("light", next); localStorage.setItem("theme", next ? "light" : "dark"); return next; }), []);
  useEffect(() => { const handler = (e: KeyboardEvent) => { if (chooseProduct) return; if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement || e.target instanceof HTMLSelectElement) return; if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") { e.preventDefault(); router.push("/search"); return; } if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "b") { e.preventDefault(); setSidebarOpen(prev => !prev); return; } const item = NAV_ITEMS.find(x => x.shortcut === e.key); if (item) router.push(item.href); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [router, chooseProduct]);
  const page = NAV_ITEMS.find(item => item.href === pathname)?.label ?? (pathname === "/search" ? "Search" : "Workspace");
  return <ToastProvider><div className="flex min-h-screen overflow-hidden bg-[var(--bg)]">
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-64 flex-col border-r border-[var(--border)] bg-[var(--bg-secondary)] transition-transform duration-300 md:static ${sidebarOpen ? "translate-x-0" : "-translate-x-full md:hidden"}`} aria-label="Main navigation">
      <div className="flex h-[72px] items-center gap-3 border-b border-[var(--border)] px-5"><div className="grid size-9 place-items-center rounded-xl bg-[var(--accent)] text-[var(--bg)]"><Sparkles size={18} /></div><div><p className="font-display text-sm font-bold tracking-tight">Product Discovery</p><button onClick={() => { setDraftProduct(product); setChooseProduct(true); }} className="text-left text-[10px] uppercase tracking-[.15em] text-[var(--accent)] hover:underline">{product || "Choose research"}</button></div></div>
      <nav className="flex-1 overflow-y-auto px-3 py-4">{NAV_ITEMS.map(item => { const Icon = item.icon; const active = pathname === item.href; return <Link key={item.href} href={item.href} className={`mb-1 flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition-colors ${active ? "bg-[var(--accent-light)] text-[var(--accent)]" : "text-[var(--text-secondary)] hover:bg-[var(--bg-hover)] hover:text-[var(--text)]"}`}><Icon size={17} strokeWidth={active ? 2.25 : 1.8} /><span className="flex-1">{item.label}</span><kbd className="hidden font-mono text-[10px] text-[var(--text-tertiary)] lg:block">{item.shortcut}</kbd></Link>; })}</nav>
      <div className="border-t border-[var(--border)] p-3">{session && <div className="mb-2 flex items-center gap-2.5 border-b border-[var(--border)] pb-2.5"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[var(--accent-light)] text-xs font-semibold text-[var(--accent)]">{initials}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium text-[var(--text)]">{session.name}</p><p className="truncate text-[10px] text-[var(--text-tertiary)]">{session.email}</p></div><button onClick={handleSignOut} aria-label="Sign out" title="Sign out" className="rounded-md p-1.5 text-[var(--text-tertiary)] transition-colors hover:bg-[var(--bg-hover)] hover:text-[var(--danger)]"><LogOut size={15} /></button></div>}<Link href="/search" className="mb-2 flex items-center gap-2 rounded-lg border border-[var(--border)] px-3 py-2 text-xs text-[var(--text-tertiary)] hover:bg-[var(--bg-hover)]"><Search size={14} /><span className="flex-1">Search anything</span><Command size={12} /><span>K</span></Link><button onClick={toggleTheme} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-[var(--text-secondary)] hover:bg-[var(--bg-hover)]">{light ? <Moon size={17} /> : <Sun size={17} />}<span>{light ? "Dark mode" : "Light mode"}</span></button></div>
    </aside>
    {sidebarOpen && <button aria-label="Close navigation" onClick={() => setSidebarOpen(false)} className="fixed inset-0 z-30 bg-black/45 md:hidden" />}
    <div className="flex min-w-0 flex-1 flex-col"><header className="flex h-[72px] items-center gap-3 border-b border-[var(--border)] bg-[var(--bg)] px-4 md:px-7"><button onClick={() => setSidebarOpen(prev => !prev)} className="grid size-9 place-items-center rounded-lg text-[var(--text-secondary)] hover:bg-[var(--bg-tertiary)]" aria-label="Toggle navigation">{sidebarOpen ? <PanelLeftClose size={18} /> : <PanelLeftOpen size={18} />}</button><div className="flex items-center gap-2.5"><div><p className="font-display text-base font-semibold">{page}</p><p className="text-[11px] text-[var(--text-tertiary)]">{product ? `Active research: ${product}` : "Choose a research to begin"}</p></div>{product && <button onClick={() => { setDraftProduct(product); setChooseProduct(true); }} title="Exit this research and pick another" className="rounded-lg border border-[var(--border)] px-2.5 py-1.5 text-xs font-medium text-[var(--text-secondary)] transition-colors hover:border-[var(--accent)] hover:text-[var(--accent)]">Switch</button>}</div><Link href="/search" className="ml-auto hidden items-center gap-2 rounded-lg border border-[var(--border)] bg-[var(--bg-secondary)] px-3 py-2 text-xs text-[var(--text-tertiary)] sm:flex"><Search size={14} />Search <kbd className="ml-5 font-mono">Ctrl K</kbd></Link></header><main className="flex-1 overflow-y-auto p-4 md:p-7">{ready ? children : <div className="flex h-full min-h-[40vh] items-center justify-center"><Spinner size={24} /></div>}</main></div>
    {mounted && ready && chooseProduct && <div className="fixed inset-0 z-[100] grid place-items-center bg-black/70 p-4"><div className="w-full max-w-md rounded-2xl border border-[var(--border-strong)] bg-[var(--bg-secondary)] p-6 shadow-2xl"><div className="mb-3 grid size-10 place-items-center rounded-xl bg-[var(--accent-light)] text-[var(--accent)]"><Target size={19} /></div><h2 className="font-display text-xl font-semibold">{onboarding ? "Start your product research" : products.length ? "Continue a research or start a new one" : "Start your first research"}</h2><p className="mt-2 text-sm leading-6 text-[var(--text-secondary)]">{onboarding ? "This workspace has no research yet. Start a research query or import an existing research document." : products.length ? "Pick a research below to continue where you left off, or start a new one. Each research keeps its own data, fully separate from the others." : "Name the product or initiative you are researching. You can run several research workspaces in parallel — their data stays separate."}</p>{products.length > 0 && <div className="mt-5 space-y-2">{products.map(item => <button key={item.id} onClick={() => selectProduct(item)} className="flex w-full items-center justify-between gap-3 rounded-lg border border-[var(--border)] px-3 py-3 text-left transition-colors hover:border-[var(--accent)] hover:bg-[var(--bg-hover)]"><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{item.name}</span><span className="block text-xs text-[var(--text-tertiary)]">{item.researchCount || 0} research · updated {new Date(item.updatedAt).toLocaleDateString()}</span></span><span className="shrink-0 text-xs font-semibold text-[var(--accent)]">Continue →</span></button>)}</div>}<><label className="mt-5 block text-xs font-medium text-[var(--text-secondary)]">New research name</label><input autoFocus={products.length === 0} value={draftProduct} onChange={event => setDraftProduct(event.target.value)} onKeyDown={event => { if (event.key === "Enter") saveProduct(); }} placeholder="e.g. Virtual Card Middleware" className="mt-2 w-full rounded-lg border border-[var(--border)] bg-[var(--bg)] px-3 py-2.5 text-sm outline-none focus:border-[var(--accent)]" /><button onClick={saveProduct} disabled={!draftProduct.trim()} className="mt-4 w-full rounded-lg bg-[var(--accent)] px-4 py-2.5 text-sm font-semibold text-[var(--bg)] disabled:opacity-50">Start new research</button></><div className="mt-5 grid grid-cols-2 gap-3"><Link href="/research" onClick={() => setChooseProduct(false)} className="rounded-lg bg-[var(--accent)] px-3 py-3 text-center text-sm font-semibold text-[var(--bg)]">Start research</Link><Link href="/import" onClick={() => setChooseProduct(false)} className="rounded-lg border border-[var(--border)] px-3 py-3 text-center text-sm font-semibold hover:bg-[var(--bg-hover)]">Import document</Link></div></div></div>}
  </div></ToastProvider>;
}
